version: '3.7'

services:
  web:
    env_file:
      - ./core/.env.prod
    build: ./core
    expose:
      - 8000
    volumes:
      - media-data:/vol/media
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - media-data:/vol/media
      - certbot-data:/var/www/certbot

volumes:
  media-data:
  certbot-data:
    driver: local