# Generated by Django 5.0.1 on 2024-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(verbose_name='Тип задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasks/', verbose_name='Фотография')),
                ('correct_answer', models.CharField(max_length=128, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
