# Generated by Django 5.0.1 on 2024-01-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название формулы')),
                ('formula', models.CharField(max_length=32, verbose_name='Формула')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exam.formulacategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
            },
        ),
    ]
